spring:
  datasource:
    url: jdbc:mysql://localhost:3306/courses?useSSL=false
    username: root
    password: ADMIN12345


#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER
#
#  # The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  #JPA Settings
  jpa.hibernate.ddl_auto: create